color0 #291d14
color1 #f2a169
color2 #f2a169
color3 #f2e569
color4 #baf269
color5 #f5b58a
color6 #f5eb8a
color7 #f3f2f2
color8 #74675f
color9 #f2a169
color10 #f2a169
color11 #f2e569
color12 #baf269
color13 #f5b58a
color14 #f5eb8a
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291d14
background            #291d14
foreground            #f3f2f2
selection_foreground  #b6b2af
selection_background  #37261b
url_color             #f2a169
