cursor #dce3ee
cursor_text_color #c0c7d1

foreground            #dce3ee
background            #0d141b
selection_foreground  #212e4b
selection_background  #b8c6ea
url_color             #97cbff

color0   #0d141b
color1   #ff729c
color2   #7fff90
color3   #fff772
color4   #7bb6f2
color5   #005687
color6   #97cbff
color7   #eff9ff
color8   #3d4346
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #a6d2ff
color13  #b6daff
color14  #d0e7ff
color15  #f8fcff
